import { User, UserRole } from '../models/User'
import { StudentProfile } from '../models/StudentProfile'
import { TeacherProfile } from '../models/TeacherProfile'
import { Parent } from '../models/Parent'

/** Two-letter ID prefix per role, used to build every user's display ID. */
export const ROLE_ID_PREFIX: Record<UserRole, string> = {
  Student: 'ST',
  Teacher: 'TE',
  Admin: 'AD',
  'Super Admin': 'SA',
  Parent: 'PA',
}

/** Deterministic, unique-by-construction display ID from a user's own row id — e.g. ST00007, TE00012. */
export function formatDisplayId(prefix: string, userId: number): string {
  return `${prefix}${String(userId).padStart(5, '0')}`
}

/** Display ID for a given role + user id, e.g. displayIdForRole('Student', 7) -> 'ST00007'. */
export function displayIdForRole(role: UserRole, userId: number): string {
  return formatDisplayId(ROLE_ID_PREFIX[role] ?? 'US', userId)
}

/** True if a stored code is empty or was clearly auto-generated by the old STU####/EMP#### scheme (safe to replace). */
function isBlankOrLegacyAutoCode(code: string | null, legacyPrefix: string, userId: number): boolean {
  if (!code) return true
  return code === `${legacyPrefix}${String(userId).padStart(4, '0')}`
}

/** Backfill/normalize a Student/Teacher/Parent's profile row and stored display ID to the canonical
 *  ST00000/TE00000 format. Leaves alone any code an admin has manually customized to something else. */
export async function ensureDisplayId(user: User): Promise<void> {
  if (user.role === 'Student') {
    const [profile] = await StudentProfile.findOrCreate({ where: { userId: user.id } })
    if (isBlankOrLegacyAutoCode(profile.studentCode, 'STU', user.id)) {
      profile.studentCode = displayIdForRole('Student', user.id)
      await profile.save()
    }
  } else if (user.role === 'Teacher') {
    const [profile] = await TeacherProfile.findOrCreate({ where: { userId: user.id } })
    if (isBlankOrLegacyAutoCode(profile.employeeCode, 'EMP', user.id)) {
      profile.employeeCode = displayIdForRole('Teacher', user.id)
      await profile.save()
    }
  } else if (user.role === 'Parent') {
    await Parent.findOrCreate({ where: { userId: user.id } })
  }
}
